cwapi:
  user: kraso_cw_craft
  password: 44fE1y42SrKTLkOsfcfVKB4elywrkOtM

database:
  address: http://localhost:8529
  name: cwcraft
  username: cwcraft
  password: qw5as5zx5

sessions_secret: x72rP3532t4kDJ9K96ohaXUA
